on: push
name: CI
jobs:
  lint-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install
      uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8 # v1.0.1
      with:
        args: install
    - name: Lint
      uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8 # v1.0.1
      with:
        args: lint
    - name: Test
      uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8 # v1.0.1
      with:
        args: test
